name: xml2rfc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with xml2rfc
      run: |
        pip install xml2rfc
        xml2rfc draft-dns-zone-digest.xml && cat draft-dns-zone-digest.txt
    - name: Commit updated file
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Regenerate .txt"
        add: draft-dns-zone-digest.txt
    - name: Push I-D file
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
